version: '3.5'

services:
    postgres:
        image: postgres:14
        container_name: postgres-conquerors
        networks:
            - conquerors
        environment:
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            POSTGRES_USER: "${DB_USERNAME}"
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
    server:
        container_name: conquerors-server
        image: conquerors-server:1.0
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev
        depends_on:
            - postgres
        networks:
            - conquerors
    adminer:
        image: adminer
        container_name: conquerors-adminer
        restart: always
        ports:
            - "8080:8080"
        networks:
            - conquerors

networks:
    conquerors:
        external:
            name: conquerors

volumes:
    postgres:
