export const DISTRICTS = [
  {id: '1', name: 'Quận 1'},
  {id: '2', name: 'Quận 2'},
  {id: '3', name: 'Quận 3'},
  {id: '4', name: 'Quận 4'},
  {id: '5', name: 'Quận 5'},
  {id: '6', name: 'Quận 6'},
  {id: '7', name: 'Quận 7'},
  {id: '8', name: 'Quận 8'},
  {id: '9', name: 'Quận 9'},
  {id: '10', name: 'Quận 10'},
  {id: '11', name: 'Quận 11'},
  {id: '12', name: 'Quận 12'},
  {id: '13', name: 'Quận Bình Tân'},
  {id: '14', name: 'Quận Bình Thạnh'},
  {id: '15', name: 'Quận Gò Vấp'},
  {id: '16', name: 'Quận Phú Nhuận'},
  {id: '17', name: 'Quận Tân Bình'},
  {id: '18', name: 'Quận Tân Phú'},
  {id: '19', name: 'Quận Thủ Đức'},
  {id: '20', name: 'Huyện Bình Chánh'},
  {id: '21', name: 'Huyện Cần Giờ'},
  {id: '22', name: 'Huyện Củ Chi'},
  {id: '23', name: 'Huyện Hóc Môn'},
  {id: '24', name: 'Huyện Nhà Bè'}
]
